### ISSUE TITLE
Dashboard Homepage

### ISSUE THREAD

**Issue by CactusHydroxide** [CactusHydroxide/GoubaResources#6]
Dashboard homepage to show whats currently on-going and upcoming in HSR.  Also gouba advert 😎 

DOD:

- [ ] Current Event
- [ ] Upcoming Event
- [ ] Current Banners
- [ ] Upcoming/Previous half Banner
- [ ] Latest Gouba Video
- [ ] Quick Links to ?? (maybe social media and whatever is going on rn)
